### ISSUE TITLE
Submit package to PyPI

### ISSUE THREAD

**Issue by TiberiumN** [TiberiumN/pippy#1]
Make package setup-friendly and sumbit it to PyPI

**Comment by jamesguessis** [comment]
Is your pippy on PyPI yet

**Comment by TiberiumN** [comment]
@jamesguessis no, but you can do it in your fork :)

**Comment by jamesguessis** [comment]
Should I rename the package to osu-calc?

**Comment by TiberiumN** [comment]
@jamesguessis why?
Search on PyPI is done not only by name, but by a short description too.
You can keep name the same, and add short description on PyPI like "pippy is a parser for osu! game beatmaps and pp calculator" like that. It's up to you.
I'm glad that my code is useful to someone :)

**Comment by jamesguessis** [comment]
Ahhh I wasn't aware that it works like that
I'm still pretty new to python/coding in general
The code is actually very useful for me and my friend Thank you :D

**Comment by jamesguessis** [comment]
What's the license pippy uses 👀

**Comment by TiberiumN** [comment]
@jamesguessis oh, it uses GPLv3, but if you want MIT, I can change it

**Comment by jamesguessis** [comment]
I don't know the difference between them 👀

**Comment by TiberiumN** [comment]
@jamesguessis it's hard to explain, I'll just change it to MIT :)

**Comment by TiberiumN** [comment]
@jamesguessis https://github.com/jamesguessis/pippy-json/pull/1

**Comment by jamesguessis** [comment]
https://pypi.python.org/pypi?name=osupippy I think I did it? I'm not sure if it works or not, I only followed a tutorial of how to do it 😛

**Comment by TiberiumN** [comment]
@jamesguessis I think you didn't :)

**Comment by jamesguessis** [comment]
https://pypi.python.org/pypi?name=osupippy&version=0.1&:action=display *
I accidentally only copied part of the url 🤐
